### ISSUE TITLE
RUM Sessions and Error tracking blue selection is not updated when users switches between them

### ISSUE THREAD

**Issue by neha00290** [openobserve/openobserve#1724]
### Which OpenObserve functionalities are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Steps-
1. Go to RUM UI
2. Switch between Sessions and Error tabs
3. Observe the blue selection
[screen-capture (3).webm](https://github.com/openobserve/openobserve/assets/144308844/330fcbea-8f29-49ce-9e3c-ccd06c71458d)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version
Commit Hash
Build Date
v0.6.4
be240a29e2679eb0e279f2a3ef645fdae48b75d7
2023-10-23T10:56:48Z
```

**Comment by omkarK06** [comment]
This issue has been fixed in #1759

**Comment by neha00290** [comment]
this still not working properly if i select these options and click browser back
Steps
1. Go to sessions and then go to error tracking
2. Select both few more times and then click browser back and forward page.
3. Observe the selection of tabs
@bjp232004  @omkarK06
