### ISSUE TITLE
Data sizes in UI is negative

### ISSUE THREAD

**Issue by henrikschristensen** [openobserve/openobserve#5692]
### Which OpenObserve functionalities are the source of the bug?

home, streams

### Is this a regression?

Yes

### Description

on the home screen and streams screen in the UI Ingested and Compressed data sizes is negative.
Running on Windows Server 2022. Single instance. Metadata in Postgres.
![image](https://github.com/user-attachments/assets/ef417268-08e2-4282-90ae-7fc536a5de0d)
![image](https://github.com/user-attachments/assets/5f6ab2ee-6326-415d-a31a-ecfd59ce7223)

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: 0.14.0
```

**Comment by hengfeiyang** [comment]
fixed, will release in next version `v0.14.3`

**Comment by gaby** [comment]
@hengfeiyang This is still an issue. The sizes are negative for some of the  `Metric Streams` in the streams page.

Running v0.14.3 / Docker

**Comment by hengfeiyang** [comment]
Reset stats once, single node stop it first, cluster mode, stop compactor first. then run the reset command:
```
./openobserve reset -c stream-stats
```
then start all service, it will be fine.

**Comment by gaby** [comment]
@hengfeiyang Because of the way O2 Docker is shipped, you can't run that in the container. It needs a shell 😂

**Comment by hengfeiyang** [comment]
i assume you know that, use `v0.14.3-debug` this image allow you to login.

**Comment by gaby** [comment]
Didnt know, will try that and revert back to non-debug tag
