### ISSUE TITLE
On this path, Logs-> List Scheduled Search -> Streams -> Logs, Histogram does not load

### ISSUE THREAD

**Issue by Shrinath-O2** [openobserve/openobserve#7354]
### Which OpenObserve functionalities are the source of the bug?

log search

### Is this a regression?

Yes

### Description

Ideally the histogram should reload

### Please provide the exception or error you saw

```true

```

### Please provide the version you discovered this bug in (check about page for version information)

```true
Version: v0.14.6-rc7-pb10
Commit Hash: 17ffa85010700f097e4bd476a3024873312a1cde
Build Date: 2025-06-25T05:12:03Z
```

**Comment by Shrinath-O2** [comment]
Histogram error is now fixed. However, we are getting this error message now - 

![Image](https://github.com/user-attachments/assets/60a764cd-7f6a-4835-ab73-1238b3acce38)

**Comment by bjp232004** [comment]
Solution: User redirect from streams to logs page, URL will have type params which we have to remove once user press Run Query button on logs page.

**Comment by neha00290** [comment]
This issue is still reproducible. The label has been updated accordingly to reflect the current status.

**Comment by neha00290** [comment]
## Bug Verification Report

**Status:** ✅ FIXED  
**Tested on:** 2026-05-20  


### Reproduction Path Tested
1. Logs → More Options → List Scheduled Search
2. Clicked on search job (root@example.com, Finished)
3. Navigated to Streams
4. Navigated back to Logs
5. Pressed "Run Query"

### Result
No "Undefined Length" error observed. No console errors. The URL contains `stream_type=logs` param but the error no longer appears after Run Query is pressed.

---
🧪 Verified by Test-Assist

**Comment by neha00290** [comment]
https://github.com/openobserve/openobserve/pull/12061
