### ISSUE TITLE
[Panic] index out of bounds in async_file.rs:202 when querying logs (v0.20.0-rc2)

### ISSUE THREAD

**Issue by numen06** [openobserve/openobserve#9406]
In OpenObserve v0.20.0-rc2, log ingestion works fine, but search queries fail with a panic:

2025-12-01T04:43:35.507719161+00:00 INFO openobserve::service::search::grpc::storage: [trace_id 019ad83926c57902a5dd867f428bde42-BTDEsMJ] search->storage: enter
2025-12-01T04:43:35.507737068+00:00 INFO openobserve::service::search::grpc::storage: [trace_id 019ad83926c57902a5dd867f428bde42-BTDEsMJ] search->storage: stream default/logs/gateway_logs, get schema versions num 1
2025-12-01T04:43:35.507763494+00:00 INFO openobserve::service::search::grpc::storage: [trace_id 019ad83926c57902a5dd867f428bde42-BTDEsMJ] search->storage: stream default/logs/gateway_logs, load file_list num 49
2025-12-01T04:43:35.507776284+00:00 INFO openobserve::service::search::grpc::storage: [trace_id 019ad83926c57902a5dd867f428bde42-BTDEsMJ] search->storage: stream default/logs/gateway_logs, load files 49, scan_size 281356037, compressed_size 5887773
2025-12-01T04:43:35.507893887+00:00 INFO openobserve::service::search::grpc::storage: [trace_id 019ad83926c57902a5dd867f428bde42-BTDEsMJ] search->storage: stream default/logs/gateway_logs, load files 49, memory cached 0, disk cached 0, cached ratio 0%, took: 0 ms
2025-12-01T04:43:35.508305486+00:00 INFO openobserve::service::search::grpc::storage: [trace_id 019ad83926c57902a5dd867f428bde42-BTDEsMJ] search->storage: create tables took: 0 ms
2025-12-01T04:43:35.508326839+00:00 INFO openobserve::service::search::grpc::flight: [trace_id 019ad83926c57902a5dd867f428bde42-BTDEsMJ] flight->search: storage search completed, 49 files
thread 'grpc_runtime' (32) panicked at /openobserve/src/config/src/utils/async_file.rs:202:20:
index out of bounds: the len is 12 but the index is 12
2025-12-01T04:43:35.509821521+00:00 INFO openobserve::service::search::datafusion::distributed_plan::common: [trace_id 019ad83926c57902a5dd867f428bde42] flight->search: response node: http://10.0.1.110:5081, is_querier: true, err: Status { code: Cancelled, message: "h2 protocol error: http2 error", source: Some(tonic::transport::Error(Transport, hyper::Error(Http2, Error { kind: Reset(StreamId(35), CANCEL, Remote) }))) }, took: 6 ms
2025-12-01T04:43:35.509908830+00:00 INFO openobserve::service::search::cluster::flight: [trace_id 019ad83926c57902a5dd867f428bde42] flight->search: datafusion collect done
2025-12-01T04:43:35.510128490+00:00 INFO openobserve::service::search::cluster::flight: [trace_id 019ad83926c57902a5dd867f428bde42] flight->search: search finished
2025-12-01T04:43:35.510146020+00:00 INFO openobserve::service::search::cluster::flight: [trace_id 019ad83926c57902a5dd867f428bde42] release lock in flight search
2025-12-01T04:43:35.510159012+00:00 INFO openobserve::service::search::cluster::http: [trace_id 019ad83926c57902a5dd867f428bde42] search->result: total: 0, scan_size: 0 mb, took: 15 ms
2025-12-01T04:43:35.510192945+00:00 INFO openobserve::service::search: [trace_id 019ad83926c57902a5dd867f428bde42] in leader task finish
2025-12-01T04:43:35.510264621+00:00 INFO openobserve::service::search::cache: [trace_id 019ad83926c57902a5dd867f428bde42] cache done
2025-12-01T04:43:35.510699187+00:00 INFO actix_web::middleware::logger: 10.0.1.84 "POST /api/default/_search HTTP/1.1" 200 447 "325" "-" "okhttp/4.9.1" 0.017642
2025-12-01T04:43:39.071241146+00:00 INFO actix_web::middleware::logger: 10.0.1.84 "POST /api/default/gateway_logs/_json HTTP/1.1" 200 99 "17492" "-" "okhttp/4.9.1" 0.002051

**Comment by prabhatsharma** [comment]
Fixed in https://github.com/openobserve/openobserve/pull/9402 . Please upgrade to `v0.20.1`

**Comment by KunLiu1210** [comment]
The bug still persists even after upgrading to the new version v0.20.1

> Fixed in [#9402](https://github.com/openobserve/openobserve/pull/9402) . Please upgrade to `v0.20.1`

https://github.com/openobserve/openobserve/issues/9423

**Comment by hengfeiyang** [comment]
checked your error logs, you are still running old version. new version fixed the panic.

**Comment by KunLiu1210** [comment]
> checked your error logs, you are still running old version. new version fixed the panic.

sorry,The logs below are from the latest version.

12-02T07:46:06.068130345+00:00 INFO openobserve::service::search::datafusion::distributed_plan::remote_scan_exec: [trace_id 019ade069ad970a092ab7c4b8e9a754b-1] flight->search: request node: http://172.80.61.3:5081, name: 513c8edf87e7, query_type: ui, is_super: false, is_querier: true, timeout: 600, files: 0
2025-12-02T07:46:06.068155263+00:00 INFO openobserve::service::search::datafusion::distributed_plan::remote_scan_exec: [trace_id 019ade069ad970a092ab7c4b8e9a754b-1] flight->search: prepare to request node: http://172.80.61.3:5081, name: 513c8edf87e7, is_super: false, is_querier: true
2025-12-02T07:46:06.068209172+00:00 DEBUG tower::buffer::worker: service.ready=true processing request
2025-12-02T07:46:06.068768716+00:00 DEBUG h2::codec::framed_write: send frame=Headers { stream_id: StreamId(3), flags: (0x4: END_HEADERS) }
2025-12-02T07:46:06.068806386+00:00 DEBUG h2::codec::framed_write: send frame=Data { stream_id: StreamId(3) }
2025-12-02T07:46:06.068863751+00:00 DEBUG h2::codec::framed_write: send frame=Data { stream_id: StreamId(3), flags: (0x1: END_STREAM) }
2025-12-02T07:46:06.069187928+00:00 DEBUG h2::codec::framed_read: received frame=Headers { stream_id: StreamId(3), flags: (0x4: END_HEADERS) }
2025-12-02T07:46:06.069331886+00:00 DEBUG h2::codec::framed_read: received frame=Data { stream_id: StreamId(3) }
2025-12-02T07:46:06.069381990+00:00 DEBUG h2::codec::framed_read: received frame=Data { stream_id: StreamId(3), flags: (0x1: END_STREAM) }
2025-12-02T07:46:06.069573956+00:00 INFO openobserve::handler::grpc::flight: [trace_id 019ade069ad970a092ab7c4b8e9a754b-1-qPjeeYz] flight->search: do_get, timeout: 600s
2025-12-02T07:46:06.069605265+00:00 INFO openobserve::service::search::grpc::flight: [trace_id 019ade069ad970a092ab7c4b8e9a754b-1-qPjeeYz] flight->search: start
2025-12-02T07:46:06.070732460+00:00 DEBUG datafusion_execution::memory_pool::pool: Created new FairSpillPool(pool_size=25769803776)
2025-12-02T07:46:06.071069426+00:00 DEBUG datafusion_functions_json: Overwrite existing UDF: json_get
2025-12-02T07:46:06.071078503+00:00 DEBUG datafusion_functions_json: Overwrite existing UDF: json_get_bool
2025-12-02T07:46:06.071082204+00:00 DEBUG datafusion_functions_json: Overwrite existing UDF: json_get_float
2025-12-02T07:46:06.071085864+00:00 DEBUG datafusion_functions_json: Overwrite existing UDF: json_get_int
2025-12-02T07:46:06.071089438+00:00 DEBUG datafusion_functions_json: Overwrite existing UDF: json_get_json
2025-12-02T07:46:06.071092963+00:00 DEBUG datafusion_functions_json: Overwrite existing UDF: json_get_array
2025-12-02T07:46:06.071096359+00:00 DEBUG datafusion_functions_json: Overwrite existing UDF: json_as_text
2025-12-02T07:46:06.071099913+00:00 DEBUG datafusion_functions_json: Overwrite existing UDF: json_get_str
2025-12-02T07:46:06.071103447+00:00 DEBUG datafusion_functions_json: Overwrite existing UDF: json_contains
2025-12-02T07:46:06.071107694+00:00 DEBUG datafusion_functions_json: Overwrite existing UDF: json_length
2025-12-02T07:46:06.071111623+00:00 DEBUG datafusion_functions_json: Overwrite existing UDF: json_object_keys
2025-12-02T07:46:06.071412514+00:00 DEBUG sqlparser::parser: Parsing sql 'detect_engine_logs'...
2025-12-02T07:46:06.071438406+00:00 INFO openobserve::service::search::grpc::flight: [trace_id 019ade069ad970a092ab7c4b8e9a754b-1-qPjeeYz] flight->search: part_id: 0, stream: default/logs/detect_engine_logs
2025-12-02T07:46:06.071753330+00:00 INFO openobserve::service::search::grpc::flight: [trace_id 019ade069ad970a092ab7c4b8e9a754b-1-qPjeeYz] flight->search: use_inverted_index: true, index_condition: Some(ALL), index_optimizer_rule: Some(SimpleSelect(51, false))

thread 'grpc_runtime' panicked at /openobserve/src/config/src/utils/async_file.rs:202:20:
index out of bounds: the len is 12 but the index is 12
stack backtrace:
   0:     0x55799d14fd53 - <unknown>
   1:     0x55799701fd33 - <unknown>
   2:     0x55799d14b633 - <unknown>
   3:     0x55799d14fbb2 - <unknown>
   4:     0x55799d152539 - <unknown>
   5:     0x55799d1520b8 - <unknown>
   6:     0x55799d152c8c - <unknown>
   7:     0x55799d152a3a - <unknown>
   8:     0x55799d150229 - <unknown>
   9:     0x55799d1526ed - <unknown>
  10:     0x55799701cec0 - <unknown>
  11:     0x55799701d0a2 - <unknown>
  12:     0x55799a1e9e1c - <unknown>
  13:     0x55799a1eb5ba - <unknown>
  14:     0x55799ae36182 - <unknown>
  15:     0x55799a1b4c63 - <unknown>
  16:     0x55799b889bc0 - <unknown>
  17:     0x55799b8780c4 - <unknown>
  18:     0x55799b8618c2 - <unknown>
  19:     0x55799b45a865 - <unknown>
  20:     0x55799b455fb8 - <unknown>
  21:     0x55799bd2d1d8 - <unknown>
  22:     0x55799bccbbed - <unknown>
  23:     0x55799c3dd034 - <unknown>
  24:     0x55799d3e0e36 - <unknown>
  25:     0x55799c40b286 - <unknown>
  26:     0x55799b9bd302 - <unknown>
  27:     0x55799c418eee - <unknown>
  28:     0x55799c07ac00 - <unknown>
  29:     0x55799d3471e7 - <unknown>
  30:     0x55799d345d72 - <unknown>
  31:     0x55799d34d677 - <unknown>
  32:     0x55799d32cf06 - <unknown>
  33:     0x55799d32f97c - <unknown>
  34:     0x55799d155f27 - <unknown>
  35:     0x7fce231451f5 - <unknown>
  36:     0x7fce231c4b40 - __clone
  37:                0x0 - <unknown>
2025-12-02T07:46:06.073100290+00:00 DEBUG h2::codec::framed_write: send frame=Reset { stream_id: StreamId(3), error_code: CANCEL }
2025-12-02T07:46:06.073189744+00:00 DEBUG h2::codec::framed_read: received frame=Reset { stream_id: StreamId(3), error_code: CANCEL }
2025-12-02T07:46:06.073279599+00:00 INFO openobserve::service::search::datafusion::distributed_plan::common: [trace_id 019ade069ad970a092ab7c4b8e9a754b-1] flight->search: response node: http://172.80.61.3:5081, is_querier: true, err: Status { code: Cancelled, message: "h2 protocol error: http2 error", source: Some(tonic::transport::Error(Transport, hyper::Error(Http2, Error { kind: Reset(StreamId(3), CANCEL, Remote) }))) }, took: 5 ms

**Comment by KunLiu1210** [comment]
> checked your error logs, you are still running old version. new version fixed the panic.

sorry,The logs below are from the latest version.

12-02T07:46:06.068130345+00:00 INFO openobserve::service::search::datafusion::distributed_plan::remote_scan_exec: [trace_id 019ade069ad970a092ab7c4b8e9a754b-1] flight->search: request node: http://172.80.61.3:5081, name: 513c8edf87e7, query_type: ui, is_super: false, is_querier: true, timeout: 600, files: 0
2025-12-02T07:46:06.068155263+00:00 INFO openobserve::service::search::datafusion::distributed_plan::remote_scan_exec: [trace_id 019ade069ad970a092ab7c4b8e9a754b-1] flight->search: prepare to request node: http://172.80.61.3:5081, name: 513c8edf87e7, is_super: false, is_querier: true
2025-12-02T07:46:06.068209172+00:00 DEBUG tower::buffer::worker: service.ready=true processing request
2025-12-02T07:46:06.068768716+00:00 DEBUG h2::codec::framed_write: send frame=Headers { stream_id: StreamId(3), flags: (0x4: END_HEADERS) }
2025-12-02T07:46:06.068806386+00:00 DEBUG h2::codec::framed_write: send frame=Data { stream_id: StreamId(3) }
2025-12-02T07:46:06.068863751+00:00 DEBUG h2::codec::framed_write: send frame=Data { stream_id: StreamId(3), flags: (0x1: END_STREAM) }
2025-12-02T07:46:06.069187928+00:00 DEBUG h2::codec::framed_read: received frame=Headers { stream_id: StreamId(3), flags: (0x4: END_HEADERS) }
2025-12-02T07:46:06.069331886+00:00 DEBUG h2::codec::framed_read: received frame=Data { stream_id: StreamId(3) }
2025-12-02T07:46:06.069381990+00:00 DEBUG h2::codec::framed_read: received frame=Data { stream_id: StreamId(3), flags: (0x1: END_STREAM) }
2025-12-02T07:46:06.069573956+00:00 INFO openobserve::handler::grpc::flight: [trace_id 019ade069ad970a092ab7c4b8e9a754b-1-qPjeeYz] flight->search: do_get, timeout: 600s
2025-12-02T07:46:06.069605265+00:00 INFO openobserve::service::search::grpc::flight: [trace_id 019ade069ad970a092ab7c4b8e9a754b-1-qPjeeYz] flight->search: start
2025-12-02T07:46:06.070732460+00:00 DEBUG datafusion_execution::memory_pool::pool: Created new FairSpillPool(pool_size=25769803776)
2025-12-02T07:46:06.071069426+00:00 DEBUG datafusion_functions_json: Overwrite existing UDF: json_get
2025-12-02T07:46:06.071078503+00:00 DEBUG datafusion_functions_json: Overwrite existing UDF: json_get_bool
2025-12-02T07:46:06.071082204+00:00 DEBUG datafusion_functions_json: Overwrite existing UDF: json_get_float
2025-12-02T07:46:06.071085864+00:00 DEBUG datafusion_functions_json: Overwrite existing UDF: json_get_int
2025-12-02T07:46:06.071089438+00:00 DEBUG datafusion_functions_json: Overwrite existing UDF: json_get_json
2025-12-02T07:46:06.071092963+00:00 DEBUG datafusion_functions_json: Overwrite existing UDF: json_get_array
2025-12-02T07:46:06.071096359+00:00 DEBUG datafusion_functions_json: Overwrite existing UDF: json_as_text
2025-12-02T07:46:06.071099913+00:00 DEBUG datafusion_functions_json: Overwrite existing UDF: json_get_str
2025-12-02T07:46:06.071103447+00:00 DEBUG datafusion_functions_json: Overwrite existing UDF: json_contains
2025-12-02T07:46:06.071107694+00:00 DEBUG datafusion_functions_json: Overwrite existing UDF: json_length
2025-12-02T07:46:06.071111623+00:00 DEBUG datafusion_functions_json: Overwrite existing UDF: json_object_keys
2025-12-02T07:46:06.071412514+00:00 DEBUG sqlparser::parser: Parsing sql 'detect_engine_logs'...
2025-12-02T07:46:06.071438406+00:00 INFO openobserve::service::search::grpc::flight: [trace_id 019ade069ad970a092ab7c4b8e9a754b-1-qPjeeYz] flight->search: part_id: 0, stream: default/logs/detect_engine_logs
2025-12-02T07:46:06.071753330+00:00 INFO openobserve::service::search::grpc::flight: [trace_id 019ade069ad970a092ab7c4b8e9a754b-1-qPjeeYz] flight->search: use_inverted_index: true, index_condition: Some(ALL), index_optimizer_rule: Some(SimpleSelect(51, false))

thread 'grpc_runtime' panicked at /openobserve/src/config/src/utils/async_file.rs:202:20:
index out of bounds: the len is 12 but the index is 12
stack backtrace:
   0:     0x55799d14fd53 - <unknown>
   1:     0x55799701fd33 - <unknown>
   2:     0x55799d14b633 - <unknown>
   3:     0x55799d14fbb2 - <unknown>
   4:     0x55799d152539 - <unknown>
   5:     0x55799d1520b8 - <unknown>
   6:     0x55799d152c8c - <unknown>
   7:     0x55799d152a3a - <unknown>
   8:     0x55799d150229 - <unknown>
   9:     0x55799d1526ed - <unknown>
  10:     0x55799701cec0 - <unknown>
  11:     0x55799701d0a2 - <unknown>
  12:     0x55799a1e9e1c - <unknown>
  13:     0x55799a1eb5ba - <unknown>
  14:     0x55799ae36182 - <unknown>
  15:     0x55799a1b4c63 - <unknown>
  16:     0x55799b889bc0 - <unknown>
  17:     0x55799b8780c4 - <unknown>
  18:     0x55799b8618c2 - <unknown>
  19:     0x55799b45a865 - <unknown>
  20:     0x55799b455fb8 - <unknown>
  21:     0x55799bd2d1d8 - <unknown>
  22:     0x55799bccbbed - <unknown>
  23:     0x55799c3dd034 - <unknown>
  24:     0x55799d3e0e36 - <unknown>
  25:     0x55799c40b286 - <unknown>
  26:     0x55799b9bd302 - <unknown>
  27:     0x55799c418eee - <unknown>
  28:     0x55799c07ac00 - <unknown>
  29:     0x55799d3471e7 - <unknown>
  30:     0x55799d345d72 - <unknown>
  31:     0x55799d34d677 - <unknown>
  32:     0x55799d32cf06 - <unknown>
  33:     0x55799d32f97c - <unknown>
  34:     0x55799d155f27 - <unknown>
  35:     0x7fce231451f5 - <unknown>
  36:     0x7fce231c4b40 - __clone
  37:                0x0 - <unknown>
2025-12-02T07:46:06.073100290+00:00 DEBUG h2::codec::framed_write: send frame=Reset { stream_id: StreamId(3), error_code: CANCEL }
2025-12-02T07:46:06.073189744+00:00 DEBUG h2::codec::framed_read: received frame=Reset { stream_id: StreamId(3), error_code: CANCEL }
2025-12-02T07:46:06.073279599+00:00 INFO openobserve::service::search::datafusion::distributed_plan::common: [trace_id 019ade069ad970a092ab7c4b8e9a754b-1] flight->search: response node: http://172.80.61.3:5081, is_querier: true, err: Status { code: Cancelled, message: "h2 protocol error: http2 error", source: Some(tonic::transport::Error(Transport, hyper::Error(Http2, Error { kind: Reset(StreamId(3), CANCEL, Remote) }))) }, took: 5 ms

**Comment by hengfeiyang** [comment]
```
/openobserve/src/config/src/utils/async_file.rs:202:20:
```
That is the same issue what we fixed.  What is the version are you using? what is the image tag?

**Comment by KunLiu1210** [comment]
> ```
> /openobserve/src/config/src/utils/async_file.rs:202:20:
> ```
> 
> That is the same issue what we fixed. What is the version are you using? what is the image tag?

I am using the latest image from Docker Hub：

<img width="769" height="330" alt="Image" src="https://github.com/user-attachments/assets/feef17fc-d7bb-456d-aebc-a8dd199bf0b4" />

**Comment by KunLiu1210** [comment]
> ```
> /openobserve/src/config/src/utils/async_file.rs:202:20:
> ```
> 
> That is the same issue what we fixed. What is the version are you using? what is the image tag?

Looks like it was an issue on my side. I tried a few more times, and now queries work normally after restarting.
